services:
    directus:
        image: directus/directus:11.6.1
        ports:
            - 8055:8055
        volumes:
            - ./database:/directus/database
            - ./uploads:/directus/uploads
            - ./extensions:/directus/extensions
        env_file: .env
        environment:
            SECRET: "rcpyN_ccP697rxO_7VG3W1BPgBgOaaZ3"
            ADMIN_EMAIL: "admin@example.com"
            ADMIN_PASSWORD: "d1r3ctu5"  
            DB_CLIENT: "sqlite3"
            DB_FILENAME: "/directus/database/data.db"
            WEBSOCKETS_ENABLED: "true"
